[package]
name = "aoc-rs-24"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
regex = "1.11.1"


[dev-dependencies]
criterion = {version = "0.3", features=["html_reports"]}

[[bench]]
name = "d01"
harness = false
